from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class ChatCreate(BaseModel):
    """Inbound payload for POST /chats.

    Excludes `_id`/`createdAt`/`updatedAt`: those are generated by the
    server, same convention as `WalletContactCreate`.
    """

    title: str


class ChatUpdate(BaseModel):
    """Inbound payload for PATCH /chats/{id}: rename a conversation."""

    title: str | None = None


class ChatOut(BaseModel):
    """Outbound shape returned to the client: the full stored document."""

    model_config = ConfigDict(populate_by_name=True)

    id: str = Field(alias="_id")
    title: str
    createdAt: datetime
    updatedAt: datetime
