from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class ChatCreate(BaseModel):
    """Inbound payload for POST /chats.

    Excludes `_id`/`createdAt`/`updatedAt`: those are generated by the
    server, same convention as `WalletContactCreate`. `chatReference` is
    excluded for the same reason as `WalletRequestCreate.requestReference`  - 
    server-generated, so a client cannot spoof a reference.
    """

    ownerPartyRef: str
    title: str


class ChatUpdate(BaseModel):
    """Inbound payload for PATCH /chats/{id}: rename a conversation."""

    title: str | None = None


class ChatOut(BaseModel):
    """Outbound shape returned to the client: the full stored document.

    `chatReference`/`ownerPartyRef` are optional here but required in
    `ChatCreate`: chats also reach this collection through ObjectBox Sync
    from leafy-local-store, which doesn't populate them, and a stricter
    shape would turn reading one of those into a 500. Scoping a read to
    `ownerPartyRef` filters them out.
    """

    model_config = ConfigDict(populate_by_name=True)

    id: str = Field(alias="_id")
    chatReference: str | None = None
    ownerPartyRef: str | None = None
    title: str
    createdAt: datetime
    updatedAt: datetime
