from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class WalletContactCreate(BaseModel):
    """Inbound payload for POST /wallet-contacts.

    Excludes `_id`/`createdAt`/`updatedAt`: those are generated by the
    server (Mongo assigns `_id`, the router stamps the timestamps), so the
    client can never spoof them.
    """

    ownerPartyRef: str
    counterpartyArrangementReference: str
    counterpartyLabel: str
    counterpartyLookupType: Literal["phone", "email"]
    counterpartyLookupHint: str
    # Blind index of the email the owner typed, so a request can be addressed to this contact
    # without storing their address. Absent on phone contacts: there is no phone claim to match.
    counterpartyLookupDigest: str | None = None


class WalletContactUpdate(BaseModel):
    """Inbound payload for PATCH /wallet-contacts/{id}.

    Every field is optional so the client can send only what changed;
    `exclude_unset=True` in the router turns that into a partial `$set`.
    `ownerPartyRef`/`counterpartyArrangementReference` are deliberately
    absent - they identify which beneficiary this contact caches, so
    changing them would mean a different contact, not an edit of this one.
    """

    counterpartyLabel: str | None = None
    counterpartyLookupType: Literal["phone", "email"] | None = None
    counterpartyLookupHint: str | None = None
    counterpartyLookupDigest: str | None = None


class WalletContactOut(BaseModel):
    """Outbound shape returned to the client: the full stored document,
    including the server-managed fields that never appear in `Create`/`Update`.
    """

    model_config = ConfigDict(populate_by_name=True)

    id: str = Field(alias="_id")
    ownerPartyRef: str
    counterpartyArrangementReference: str
    counterpartyLabel: str
    counterpartyLookupType: Literal["phone", "email"]
    counterpartyLookupHint: str
    counterpartyLookupDigest: str | None = None
    createdAt: datetime
    updatedAt: datetime
